select ASMENSKODAS,VARDAS,PAVARDE FROM DARBUOTOJAS WHERE GIMIMOMETAI = '1988-07-20'
SELECT*FROM DARBUOTOJAS WHERE GIMIMOMETAI<'1988-07-29'
SELECT DIRBANUO, GIMIMOMETAI FROM DARBUOTOJAS WHERE DIRBANUO>'2009-10-30' AND DIRBANUO<'2012-11-11'
SELECT VARDAS, SKYRIUS_PAVADINIMAS,PROJEKTAS_ID FROM DARBUOTOJAS WHERE PROJEKTAS_ID IN(2,3)
SELECT VARDAS, PAVARDE, ASMENSKODAS FROM DARBUOTOJAS WHERE VARDAS NOT LIKE '%S'
SELECT*FROM DARBUOTOJAS WHERE GIMIMOMETAI LIKE '%12'
SELECT * FROM PROJEKTAS WHERE PAVADINIMAS LIKE '__u%'
SELECT *FROM DARBUOTOJAS WHERE PAREIGOS IS NULL
SELECT VARDAS,PAVARDE,DIRBANUO,PAREIGOS FROM DARBUOTOJAS WHERE DIRBANUO='2011-02-12' AND PAREIGOS='programuotojas'
select VARDAS,PAVARDE,SKYRIUS_PAVADINIMAS,PROJEKTAS_ID FROM DARBUOTOJAS WHERE SKYRIUS_PAVADINIMAS='JAVA' OR PROJEKTAS_ID=1
SELECT VARDAS FROM DARBUOTOJAS WHERE VARDAS NOT LIKE 'S%'
SELECT VARDAS,DIRBANUO,GIMIMOMETAI FROM DARBUOTOJAS WHERE DIRBANUO<'2009-10-30' OR DIRBANUO>'2012-11-11'
SELECT VARDAS,PAVARDE,GIMIMOMETAI FROM DARBUOTOJAS ORDER BY GIMIMOMETAI 
SELECT VARDAS,PAVARDE,GIMIMOMETAI FROM DARBUOTOJAS ORDER BY GIMIMOMETAI DESC
SELECT MIN(PROJEKTAS_ID) as MINID,MAX(PROJEKTAS_ID) AS MAXID FROM DARBUOTOJAS 
SELECT PROJEKTAS_ID, COUNT(PROJEKTAS_ID) AS PEOPLECOUNT FROM DARBUOTOJAS GROUP BY PROJEKTAS_ID
SELECT PROJEKTAS_ID,PAREIGOS,COUNT(PAREIGOS) AS PEOPLECOUNT FROM DARBUOTOJAS GROUP BY PAREIGOS,PROJEKTAS_ID HAVING PAREIGOS='PROGRAMUOTOJAS'
SELECT PROJEKTAS_ID,PAREIGOS,COUNT(PAREIGOS) AS PEOPLECOUNT FROM DARBUOTOJAS GROUP BY PAREIGOS,PROJEKTAS_ID HAVING COUNT(*)>2
